---

- name: create faf's database schema
  command: faf-migrate-db --create-all
  sudo: yes
  sudo_user: faf

- name: stamp database as migrated to latest version
  command: faf-migrate-db --stamp-only
  sudo: yes
  sudo_user: faf

- name: init faf
  command: faf init
  sudo: yes
  sudo_user: faf
