---

- name: enable Copr repo for RHEL
  copy: src=group_abrt-faf-el7-epel-7.repo dest=/etc/yum.repos.d/
  when: ansible_distribution == 'RedHat'

- name: enable Copr repo for Fedora
  copy: src=group_abrt-faf-el7-fedora.repo dest=/etc/yum.repos.d/
  when: ansible_distribution == 'Fedora'

- name: erase faf packages
  package: name="faf-*" state=absent
  when: faf_force_reinstall

- name: install core faf packages
  package: name={{ item }} state=present
  loop: "{{ faf_packages }}"

- name: install faf problem packages
  package: name={{ item }} state=present
  loop: "{{ faf_problem_packages }}"

- name: install faf opsys packages
  package: name={{ item }} state=present
  loop: "{{ faf_opsys_packages }}"

- name: install faf action packages
  package: name={{ item }} state=present
  loop: "{{ faf_action_packages }}"

- name: install faf bugtracker packages
  package: name={{ item }} state=present
  loop: "{{ faf_bugtracker_packages }}"
  when: faf_with_bugtrackers

- name: install faf celery packages
  package: name={{ item }} state=present
  loop: "{{ faf_celery_packages }}"
  when: faf_with_celery

- name: install faf fedmsg packages
  package: name={{ item }} state=present
  loop: "{{ faf_fedmsg_packages }}"
  when: faf_with_fedmsg

- name: install faf solutionfinder packages
  package: name={{ item }} state=present
  loop: "{{ faf_solutionfinder_packages }}"
  when: faf_with_solutionfinders
